# Generated by Django 3.0.5 on 2020-07-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('faculty_name', models.CharField(default=None, max_length=100)),
                ('date', models.DateField(default=None)),
                ('time', models.CharField(default=None, max_length=10)),
                ('fees', models.FloatField(default=None)),
                ('duration', models.IntegerField(default=None)),
            ],
        ),
    ]
