# Generated by Django 3.0.5 on 2020-07-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_model_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled_Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default=None, max_length=50)),
                ('faculty_name', models.CharField(default=None, max_length=100)),
                ('date', models.DateField(default=None)),
                ('time', models.CharField(default=None, max_length=10)),
                ('fees', models.FloatField(default=None)),
                ('duration', models.IntegerField(default=None)),
                ('student_id', models.ManyToManyField(to='app.Student_Model')),
            ],
        ),
    ]
