# Generated by Django 3.0.5 on 2020-07-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_enrolled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled_courses',
            name='id',
        ),
        migrations.AddField(
            model_name='enrolled_courses',
            name='idno',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
