# Generated by Django 3.0.5 on 2020-07-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200711_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled_courses',
            name='idno',
        ),
        migrations.AddField(
            model_name='enrolled_courses',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
